# This template is intended for Self-service networks (aka OverCloud style)
---
- name: Install Horizon Package in Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-dashboard

- name: Template local_settings.py
  template:
    src: local_settings.py.j2
    dest: "/etc/openstack-dashboard/local_settings.py"
    mode: 0644
    owner: root
    group: horizon
    backup: yes

- name: Reload services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - apache2
