---
- name: Get Glance User
  shell: ". /root/admin-openrc.sh && openstack user show glance -f json"
  register: get_glance_user
  ignore_errors: True

- name: Create Glance User
  shell: ". /root/admin-openrc.sh && openstack user create --domain \"Default\" --password \"{{ glance_pass }}\" -f json glance"
  when: get_glance_user is failed

- name: Associate glance user to admin role
  shell: ". /root/admin-openrc.sh && openstack role add --project service --user glance admin"

- name: Get Glance Service
  shell: ". /root/admin-openrc.sh && openstack service show glance -f json"
  register: get_glance_service
  ignore_errors: True

- name: Create Glance Service
  shell: ". /root/admin-openrc.sh && openstack service create --name glance --description \"OpenStack Image\" -f json image"
  when: get_glance_service is failed

- name: Get Glance Endpoints
  shell: ". /root/admin-openrc.sh && openstack endpoint list -f json"
  register: get_glance_endpoints
  ignore_errors: True

- name: Parsing Endpoint JSON
  set_fact:
    glance_endpoints: "{{ get_glance_endpoints.stdout | from_json }}"
  when: get_glance_endpoints is succeeded

- name: Paring Endpoint JSON
  debug:
    var: glance_endpoints

- name: Create Glance Service Public API Endpoint
  shell: ". /root/admin-openrc.sh && openstack endpoint create -f json --region {{ openstack_region }} image public http://{{ mgmt_ip_womask }}:{{ glance_public_url_port }}"
  when: "glance_endpoints | selectattr('Service Type', 'match', '^'+'image'+'$') | selectattr('Interface', 'match', '^'+'public'+'$') | selectattr('Service Name', 'match', '^'+'glance'+'$') | selectattr('URL', 'match', '^http:\\/\\/'+(mgmt_ip_womask | regex_escape())+':'+(glance_public_url_port | string)+'$') | list | length == 0"

- name: Create Glance Service Internal API Endpoint
  shell: ". /root/admin-openrc.sh && openstack endpoint create -f json --region {{ openstack_region }} image internal http://{{ ctrl_ip_womask }}:{{ glance_internal_url_port }}"
  when: "glance_endpoints | selectattr('Service Type', 'match', '^'+'image'+'$') | selectattr('Interface', 'match', '^'+'internal'+'$') | selectattr('Service Name', 'match', '^'+'glance'+'$') | selectattr('URL', 'match', '^http:\\/\\/'+(ctrl_ip_womask | regex_escape())+':'+(glance_internal_url_port | string)+'$') | list | length == 0"

- name: Create Glance Service Admin API Endpoint
  shell: ". /root/admin-openrc.sh && openstack endpoint create -f json --region {{ openstack_region }} image admin http://{{ ctrl_ip_womask }}:{{ glance_admin_url_port }}"
  when: "glance_endpoints | selectattr('Service Type', 'match', '^'+'image'+'$') | selectattr('Interface', 'match', '^'+'admin'+'$') | selectattr('Service Name', 'match', '^'+'glance'+'$') | selectattr('URL', 'match', '^http:\\/\\/'+(ctrl_ip_womask | regex_escape())+':'+(glance_admin_url_port | string)+'$') | list | length == 0"
