# Variables for InfluxDB Datalake
influxdb_version: 1.5.3
influxdb_admin_password: admin
influxdb_user_id: test
influxdb_user_password: test
influxdb_databases:
  - tcpconnect
  - blockio
  - cpuusage

# Variables for Dashboard
grafana_version: 5.1.3
grafana_ip: "{{ hostvars[groups['dashboard'][0]]['ctrl_ip'] | ipaddr_womask_filter }}"
grafana_port: 3000
grafana_user_id: admin
grafana_user_password: admin
grafana_plugins:
datalake_ip: "{{ hostvars[groups['datalake-control'][0]]['ctrl_ip'] | ipaddr_womask_filter }}"
datalake_port: 8086
