---
- hosts: dashboard
  vars_files:
    - configurations.yaml
  roles:
    - influxdb
  tasks:
    - name: Creating InfluxDB Databases
      influxdb_database:
        database_name: "{{ item }}"
        username: "{{ influxdb_user_id }}"
        password: "{{ influxdb_user_password }}"
        state: present
      with_items: "{{ influxdb_databases }}"


- hosts: datalake-control
  vars_files:
    - configurations.yaml
  roles:
    - grafana
  tasks:
    - name: Connecting Grafana Data Source
      grafana_datasource:
        name: "{{ item }}"
        database: "{{ item }}"
        ds_type: influxdb
        url: "http://{{ datalake_ip }}:{{ datalake_port }}"
        basic_auth_user: "{{ influxdb_user_id }}"
        basic_auth_password: "{{ influxdb_user_password }}"
        grafana_url: "http://{{ grafana_ip }}:{{ grafana_port }}"
        grafana_user: "{{ grafana_user_id }}"
        grafana_password: "{{ grafana_user_password }}"
      with_items: "{{ influxdb_databases }}"
