---
# tasks file for influxdb
- name: Installing Ubuntu Packages for Python
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python
    - python-pip

- name: Installing Python Packages for InfluxDB
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - requests
    - influxdb

- name: Downloading InfluxDB {{ influxdb_version }} DEB file
  get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_{{ influxdb_version }}_amd64.deb
    dest: /tmp/influxdb.deb

- name: Installing InfluxDB {{ influxdb_version }} from the DEB file
  apt:
    deb: /tmp/influxdb.deb
  notify: Start InfluxDB Service

- name: Creating InfluxDB Admin Account
  influxdb_user:
    user_name: admin
    user_password: "{{ influxdb_admin_password }}"
    login_username: admin
    login_password: "{{ influxdb_admin_password }}"
    admin: yes
    state: present

- name: Creating InfluxDB User Account
  influxdb_user:
    user_name: "{{ influxdb_user_id }}"
    user_password: "{{ influxdb_user_password }}"
    login_username: "{{ influxdb_user_id }}"
    login_password: "{{ influxdb_user_password }}"
    admin: yes
    state: present

- name: Templating influxdb.conf
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: Restart InfluxDB Service

- name: Creating InfluxDB Databases
  influxdb_database:
    database_name: "{{ item }}"
    username: "{{ influxdb_user_id }}"
    password: "{{ influxdb_user_password }}"
    state: present
  with_items: "{{ influxdb_databases }}"
