---
- name: Install NTP server Package
  apt:
    name: chrony
    state: present
    update_cache: yes

- name: Templating NTP Configuration file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: Restart Chrony service
- meta: flush_handlers
