---
  - name: Create neutron DB for Nova
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: 127.0.0.1
      name: neutron
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Grant access to the DBs for the service for User neutron@localhost
    shell: "mysql -u root -e \"grant all privileges on {{ item }}.* to 'neutron'@'localhost' identified by '{{ neutron_db_pass }}'\""
    with_items:
    - neutron

  - name: Grant access to the DBs for the service for User neutron@0.0.0.0
    shell: "mysql -u root -e \"grant all privileges on {{ item }}.* to 'neutron'@'%' identified by '{{ neutron_db_pass }}'\""
    with_items:
    - neutron
