# This template is intended for Self-service networks (aka OverCloud style)
---
- name: "sysctl set net.ipv4.ip_forward = 1"
  sysctl:
    name: "net.ipv4.ip_forward"
    value: 1
    state: present
    sysctl_set: yes
    reload: yes

- name: "sysctl set net.ipv4.conf.all.rp_filter = 0"
  sysctl:
    name: "net.ipv4.conf.all.rp_filter"
    value: 0
    state: present
    sysctl_set: yes
    reload: yes

- name: "sysctl set net.ipv4.conf.default.rp_filter = 0"
  sysctl:
    name: "net.ipv4.conf.default.rp_filter"
    value: 0
    state: present
    sysctl_set: yes
    reload: yes

- name: Install Neutron Packages in Ubuntu (for Self-service networks)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - neutron-server
    - neutron-plugin-ml2
    - neutron-openvswitch-agent
    - neutron-l3-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- name: Template neutron.conf
  template:
    src: neutron.conf.j2
    dest: /etc/neutron/neutron.conf
    mode: 0644
    owner: root
    group: neutron
    backup: yes

- name: Template ml2_conf.ini
  template:
    src: ml2_conf.ini.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    mode: 0644
    owner: root
    group: neutron
    backup: yes

- name: Template openvswitch_agent.ini
  template:
    src: openvswitch_agent.ini.j2
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    mode: 0644
    owner: root
    group: neutron
    backup: yes

- name: Template l3_agent.ini
  template:
    src: l3_agent.ini.j2
    dest: /etc/neutron/l3_agent.ini
    mode: 0644
    owner: root
    group: neutron
    backup: yes

- name: Template dhcp_agent.ini
  template:
    src: dhcp_agent.ini.j2
    dest: /etc/neutron/dhcp_agent.ini
    mode: 0644
    owner: root
    group: neutron
    backup: yes

- name: Template dnsmasq-neutron.conf
  template:
    src: dnsmasq-neutron.conf.j2
    dest: /etc/neutron/dnsmasq-neutron.conf
    mode: 0644
    owner: root
    group: neutron
    backup: yes

- name: Ending DNSMasq
  shell: "pkill dnsmasq"
  ignore_errors: True

- name: Template metadata_agent.ini
  template:
    src: metadata_agent.ini.j2
    dest: /etc/neutron/metadata_agent.ini
    mode: 0644
    owner: root
    group: neutron
    backup: yes

- name: Populate neutron Database
  become_user: neutron
  command: "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head"

- name: Reload services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
  - nova-api
  - neutron-server
  - openvswitch-switch
  - neutron-openvswitch-agent
  - neutron-l3-agent
  - neutron-dhcp-agent
  - neutron-metadata-agent
