---
# tasks file for grafana
- name: Install Required APT Packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - adduser
    - libfontconfig

- name: Downloading Grafana "{{ grafana_version }}" DEB file
  get_url:
    url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_5.1.3_amd64.deb
    dest: /tmp/grafana.deb

- name: Installing Grafana "{{ grafana_version }}" DEB file
  apt:
    deb: /tmp/grafana.deb
    state: present

- name: Templating Grafana.ini
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    backup: yes
    mode: 0640

- name: Starting Grafana service
  systemd:
    name: grafana-server
    state: started
    daemon_reload: yes
    enabled: yes

- name: Installing Grafana Plugins
  grafana_plugin:
    name: "{{ item }}"
    state: present
  with_items: "{{ grafana_plugins }}"
  when: not((grafana_plugins is undefined) or (grafana_plugins is none))
