---
- name: Create Service Project
  shell: ". /root/admin-openrc.sh && openstack project create --domain \"Default\" --description \"Service Project\" -f json service"

- name: Create Demo Project
  shell: ". /root/admin-openrc.sh && openstack project create --domain \"Default\" --description \"Demo Project\" -f json demo"

- name: Create Demo User
  shell: ". /root/admin-openrc.sh && openstack user create --domain \"Default\" --password \"{{ demo_pass }}\" -f json demo"

- name: Create User Role
  shell: ". /root/admin-openrc.sh && openstack role create -f json user"

- name: Create User Role and Associate it to Demo
  shell: ". /root/admin-openrc.sh && openstack role add --project demo --user demo user"
