---
- name: Create Service Project
  os_project:
    cloud: smartx_cloud
    state: present
    name: service
    description: "Service Project"
    domain_id: default
    enabled: True

- name: Create Demo Project
  os_project:
    cloud: smartx_cloud
    state: present
    name: demo
    description: "Demo Project"
    domain_id: default
    enabled: True

  - name: Create Demo User
