---
  - name: Create DB for Keystone
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: 127.0.0.1
      name: keystone
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Grant access to the DB for the service
    mysql_user:
      login_host: 127.0.0.1
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: keystone
      host: "{{ item }}"
      password: "{{ keystone_db_pass }}"
      priv: keystone.*:ALL
      login_unix_socket: /var/run/mysqld/mysqld.sock
    with_items:
      - localhost
      - "%"
