---
  - name: Install Memcached Packages
    apt:
      name: "{{ item }}"
      state: present
      with_items:
        - memcached
        - python-memcached

  - name: Modify Memcached Conf File
    lineinfile:
      path: /etc/memcached.conf
      regexp: '^-l 127\.0\.0\.1'
      line: "-l {{ control_cip }}"

  - name: Restart Memcachd service
    service:
      name: memcached
      state: restart
