## For common
playground_name: k-one
openstack_distro: queens
# These variables are for "current" target host.
mgmt_ip_womask: "{{ mgmt_ip|ipaddr_womask_filter }}"
ctrl_ip_womask: "{{ ctrl_ip|ipaddr_womask_filter }}"
data_ip_womask: "{{ data_ip|ipaddr_womask_filter }}"
mgmt_ovs_bridge_name: br-ex
ovs_bridge_mappings: mgmt:br-ex
flat_network_list: mgmt
novncproxy_base_url: http://your-cloud.example.com:6080/vnc_auto.html
# These variables are for "control" target host.

# etcd_version: v3.2.7

## Passwords
admin_pass: openstack
rabbit_pass: openstack
mysql_root_password: openstack
keystone_db_pass: openstack
demo_pass: openstack
nova_pass: openstack
nova_db_pass: openstack
placement_pass: openstack
neutron_pass: openstack
neutron_db_pass: openstack
neutron_metadata_secret: METADATA_SECRET

## For Keystone
# keystone_admin_url_port: 35357
keystone_admin_url_port: 5000
keystone_internal_url_port: 5000
keystone_public_url_port: 5000
openstack_region: RegionOne

## For Glance
glance_pass: openstack
glance_db_pass: openstack
glance_admin_url_port: 9292
glance_internal_url_port: 9292
glance_public_url_port: 9292
## For Cinder
## For Nova
nova_admin_url_port: 8774
nova_internal_url_port: 8774
nova_public_url_port: 8774
placement_admin_url_port: 8778
placement_internal_url_port: 8778
placement_public_url_port: 8778
## For Neutron
neutron_admin_url_port: 9696
neutron_internal_url_port: 9696
neutron_public_url_port: 9696
## For Horizon
