## For common
playground_name: k-one
openstack_distro: queens
mgmt_ip_womask: "{{ mgmt_ip|ipaddr_womask_filter }}"
ctrl_ip_womask: "{{ ctrl_ip|ipaddr_womask_filter }}"
data_ip_womask: "{{ data_ip|ipaddr_womask_filter }}"
# etcd_version: v3.2.7

## Passwords
admin_pass: openstack
rabbit_pass: openstack
mysql_root_password: openstack
keystone_db_pass: openstack
demo_pass: openstack

## For Keystone
# keystone_admin_url_port: 35357
keystone_admin_url_port: 5000
keystone_internal_url_port: 5000
keystone_public_url_port: 5000
openstack_region: RegionOne

## For Glance
glance_pass: openstack
glance_db_pass: openstack
glance_admin_url_port: 9292
glance_internal_url_port: 9292
glance_public_url_port: 9292
## For Cinder
## For Nova
## For Neutron
## For Horizon
