---
- name: Debug IPs
  debug:
    msg: "{{ item }}"
  with_items:
  - "{{ mgmt_ip_womask }}"
  - "{{ ctrl_ip_womask }}"
  - "{{ data_ip_womask }}"

- name: list all hosts
  debug:
    
- name: "Intermediate processing: Extracting host names from hostvar"
  set_fact:
    host_list: |
        {% set res = [] -%}
        {% for host in hostvars.keys() -%}
          {% set ignored = res.extend([{'name': host, 'mgmt_ip': hostvars[host].mgmt_ip}]) -%}
        {%- endfor %}
        {{ res }}

- name: "list of hosts"
  debug:
    var: host_list

- name: Debug hostvars
  debug:
#   var: hostvars.openstack_control1
    var: hostvars.openstack_control1
