---
# vars file for keystone

# Ports for Keystone Service
keystone_admin_url_port: 35357
keystone_public_url_port: 5000
keystone_internal_url_port: 5000

openstack_region: RegionOne

# Variables for Administrative Account
clouds:
  smartx_cloud:
    profile: vexxhost
    auth:
      username: admin
      password: "{{ admin_pass }}"
      project_name: admin
      auth_url: http://"{{ ctrl_ip_womask }}":"{{ keystone_admin_url_port }}"/v3
      user_domain_name: Default
      project_domain_name: Default
    region_name: "{{ openstack_region }}"
